"""Ajout details jeu au thread

Revision ID: 0652439528f3
Revises: 973cd3e4930e
Create Date: 2025-11-12 16:53:14.796776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0652439528f3'
down_revision = '973cd3e4930e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metacritic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('released', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('platforms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('platforms')
        batch_op.drop_column('genres')
        batch_op.drop_column('website')
        batch_op.drop_column('released')
        batch_op.drop_column('metacritic')

    # ### end Alembic commands ###
