"""Add rawg_game_id and game details to Thread

Revision ID: 5d183be8e3ed
Revises: 5ec7c26646ba
Create Date: 2025-11-07 17:02:21.469214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d183be8e3ed'
down_revision = '5ec7c26646ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rawg_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('game_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('game_description', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_threads_rawg_game_id'), ['rawg_game_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_rawg_game_id'))
        batch_op.drop_column('game_description')
        batch_op.drop_column('game_image_url')
        batch_op.drop_column('rawg_game_id')

    # ### end Alembic commands ###
