"""ajout like

Revision ID: 973cd3e4930e
Revises: 5d183be8e3ed
Create Date: 2025-11-12 16:24:28.110187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973cd3e4930e'
down_revision = '5d183be8e3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'thread_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_likes')
    # ### end Alembic commands ###
